### PR TITLE
Make dept configurable

### PR DESCRIPTION
**Pull request by meredrica**
I added configuration options for the excerpt depth.
Other enhancements:
- The .excerpt variable is now always set (if the post is not long enough)
- The .more variable is set as well. (this was done by @mawenbao)
- The original post layout is also honored.
- Version number was bumped.

### CODE REVIEW

**Comment by meredrica** [comment]
I'll have a look at the travis problems asap

**Comment by meredrica** [comment]
To be honest, I have no idea why the `this.config` line fails. it works for me. It's also reported on the wrong line o_0

```
$ node --version
v6.2.2
$ npm --version
3.10.3
```

**Comment by chekun** [comment]
@meredrica 

the reason tests failed because I did't create a  `Silent Hexo` instance, so on tests it failed, in real app it's ok. I should use that for tests, my bad.

Could you rewrite the tests ?  or I will do it. 😃 

And Thank you for your contribution. 👍

**Comment by chekun** [comment]
@meredrica 

Hi, I've rewrite test script using real Hexo instance. See [commit](https://github.com/chekun/hexo-excerpt/commit/d39464259949c026f8dab57ec9d56d2fa8474343), would be nice if you confirm it solves the problem 😃

**Comment by meredrica** [comment]
looks good to me now :)

**Comment by meredrica** [comment]
doh, premature comment. i'll have to fix the tests. will do when i find time

**Comment by meredrica** [comment]
Right now I don't have time to fix the tests. Mind helping me out?

**Comment by chekun** [comment]
@meredrica okay, I will see to it.

**Comment by chekun** [comment]
@meredrica , tests are now ok and 100% coverage . You can use patch below, and push to your forked repository so that I can accept this PR. 😃 

``` bash
$ npm run test-cover

> hexo-excerpt@1.1.2 test-cover /private/tmp/hexo-excerpt
> istanbul cover --print both _mocha -- tests/*.js



  Automatic excerpt generator with excerpt_depth = 5
    ✓ post with <= 5 tags should have no excerpt
    ✓ post with > 5 tags should have excerpt
    ✓ post with <!-- more --> should return the way it is

  Automatic excerpt generator with default depth config
    ✓ post with <= 10 tags should have no excerpt
    ✓ post with > 10 tags should have excerpt
    ✓ post with <!-- more --> should return the way it is


  6 passing (8ms)

=============================================================================
Writing coverage object [/private/tmp/hexo-excerpt/coverage/coverage.json]
Writing coverage reports at [/private/tmp/hexo-excerpt/coverage]
=============================================================================
------------------|----------|----------|----------|----------|----------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------|----------|----------|----------|----------|----------------|
 lib/             |      100 |    91.67 |      100 |      100 |                |
  hexo-excerpt.js |      100 |    91.67 |      100 |      100 |                |
------------------|----------|----------|----------|----------|----------------|
All files         |      100 |    91.67 |      100 |      100 |                |
------------------|----------|----------|----------|----------|----------------|


=============================== Coverage summary ===============================
Statements   : 100% ( 28/28 )
Branches     : 91.67% ( 11/12 )
Functions    : 100% ( 1/1 )
Lines        : 100% ( 26/26 )
================================================================================
```

``` diff
diff --git a/lib/hexo-excerpt.js b/lib/hexo-excerpt.js
index 7ad9f8d..2b9aea2 100644
--- a/lib/hexo-excerpt.js
+++ b/lib/hexo-excerpt.js
@@ -6,11 +6,11 @@ const domutils = require('domutils');

 module.exports = function(db) {

-  let node_length = 10;
+  let nodeLength = 10;
   let config = this.config;

   if (config && config.excerpt_depth) {
-    node_length = parseInt(config.excerpt_depth);
+    nodeLength = parseInt(config.excerpt_depth);
   }

   return db.posts.map(post => {
@@ -41,7 +41,7 @@ module.exports = function(db) {
     let stopIndex = 1;
     // tracks how many nodes we found in total
     let index = 0;
-    for (; index < nodes.length && stopIndex <= node_length; index++) {
+    for (; index < nodes.length && stopIndex <= nodeLength; index++) {
       if (nodes[index].type === 'tag') {
         stopIndex++;
       }
diff --git a/package.json b/package.json
index a64e5aa..84b07c3 100644
--- a/package.json
+++ b/package.json
@@ -6,8 +6,8 @@
   "scripts": {
     "eslint": "eslint .",
     "jscs": "jscs .",
-    "test": "mocha tests/index.js",
-    "test-cover": "istanbul cover --print both _mocha -- tests/index.js"
+    "test": "mocha tests/*.js",
+    "test-cover": "istanbul cover --print both _mocha -- tests/*.js"
   },
   "directories": {
     "lib": "./lib"
diff --git a/tests/index.js b/tests/index.js
deleted file mode 100644
index fe13ef2..0000000
--- a/tests/index.js
+++ /dev/null
@@ -1,70 +0,0 @@
-'use strict';
-
-const should = require('chai').should();
-const Hexo = require('hexo');
-const hexoExcerptGenerator = require('../lib/hexo-excerpt');
-
-const hexo = new Hexo(__dirname, {
-  silent: true
-});
-
-let posts = [
-    {
-      path: '',
-      title: 'post with <= 10 blocks',
-      excerpt: '',
-      content: `
-<p>block 1</p>
-<p>block 2 <span>123</span></p>
-<div>block3</div>`.trim()
-    },
-    {
-      path: '',
-      title: 'post with > 10 blocks',
-      excerpt: '',
-      content: `
-<p>block 1</p>
-<p>block 2</p>
-<p>block 3</p>
-<p>block 4</p>
-<p>block 5</p>
-<p>block 6</p>
-<p>block 7</p>
-<p>block 8</p>
-<p>block 9</p>
-<p>block 10</p>
-<p>block 11</p>
-      `.trim()
-    },
-    {
-      path: '',
-      title: 'post with user defined more seperator',
-      excerpt: '',
-      content: `
-<p>block 1</p>
-<!-- more -->
-<p>block 2 <span>123</span></p>
-<div>block3</div>`.trim()
-    }
-];
-
-hexo.locals.set('posts', posts);
-
-describe('Automatic excerpt generator', () => {
-
-  let generatedPosts = hexoExcerptGenerator.call(hexo, hexo.locals.toObject());
-
-  it('post with <= 10 tags should have no excerpt', () => {
-    generatedPosts[0].data.excerpt.should.equal('');
-  });
-
-  it('post with > 10 tags should have excerpt', () => {
-    generatedPosts[1].data.excerpt.should.not.equal('');
-    generatedPosts[1].data.excerpt.should.equal('<p>block 1</p>\n<p>block 2</p>\n<p>block 3</p>\n<p>block 4</p>\n<p>block 5</p>\n');
-  });
-
-  it('post with <!-- more --> should return the way it is', () => {
-    generatedPosts[2].data.excerpt.should.equal('');
-  });
-
-});
```

tests/with-config.js

``` js
'use strict';

const should = require('chai').should();
const Hexo = require('hexo');
const hexoExcerptGenerator = require('../lib/hexo-excerpt');

const hexo = new Hexo(__dirname, {
  silent: true
});

let posts = [
    {
      path: '',
      title: 'post with <= 10 blocks',
      excerpt: '',
      layout: '',
      content: `
<p>block 1</p>
<p>block 2 <span>123</span></p>
<div>block3</div>`.trim()
    },
    {
      path: '',
      title: 'post with > 10 blocks',
      excerpt: '',
      layout: '',
      content: `
<p>block 1</p>
<p>block 2</p>
<p>block 3</p>
<p>block 4</p>
<p>block 5</p>
<p>block 6</p>
<p>block 7</p>
<p>block 8</p>
<p>block 9</p>
<p>block 10</p>
<p>block 11</p>`.trim()
    },
    {
      path: '',
      title: 'post with user defined more seperator',
      excerpt: '',
      layout: '',
      content: `
<p>block 1</p>
<!-- more -->
<p>block 2 <span>123</span></p>
<div>block3</div>`.trim()
    }
];

hexo.locals.set('posts', posts);

describe('Automatic excerpt generator with excerpt_depth = 5', () => {

  hexo.config.excerpt_depth = 5;

  let generatedPosts = hexoExcerptGenerator.call(hexo, hexo.locals.toObject());

  it('post with <= 5 tags should have no excerpt', () => {
    generatedPosts[0].data.excerpt.should.equal('<p>block 1</p>\n<p>block 2 <span>123</span></p>\n<div>block3</div>');
  });

  it('post with > 5 tags should have excerpt', () => {
    generatedPosts[1].data.excerpt.should.not.equal('');
    generatedPosts[1].data.excerpt.should.equal('<p>block 1</p>\n<p>block 2</p>\n<p>block 3</p>\n<p>block 4</p>\n<p>block 5</p>');
  });

  it('post with <!-- more --> should return the way it is', () => {
    generatedPosts[2].data.excerpt.should.equal('');
  });

});
```

tests/without-config.js

``` js
'use strict';

const should = require('chai').should();
const Hexo = require('hexo');
const hexoExcerptGenerator = require('../lib/hexo-excerpt');

const hexo = new Hexo(__dirname, {
  silent: true
});

let posts = [
    {
      path: '',
      title: 'post with <= 10 blocks',
      excerpt: '',
      layout: '',
      content: `
<p>block 1</p>
<p>block 2 <span>123</span></p>
<div>block3</div>`.trim()
    },
    {
      path: '',
      title: 'post with > 10 blocks',
      excerpt: '',
      layout: '',
      content: `
<p>block 1</p>
<p>block 2</p>
<p>block 3</p>
<p>block 4</p>
<p>block 5</p>
<p>block 6</p>
<p>block 7</p>
<p>block 8</p>
<p>block 9</p>
<p>block 10</p>
<p>block 11</p>`.trim()
    },
    {
      path: '',
      title: 'post with user defined more seperator',
      excerpt: '',
      layout: '',
      content: `
<p>block 1</p>
<!-- more -->
<p>block 2 <span>123</span></p>
<div>block3</div>`.trim()
    }
];

hexo.locals.set('posts', posts);

describe('Automatic excerpt generator with default depth config', () => {

  hexo.config.excerpt_depth = null;

  let generatedPosts = hexoExcerptGenerator.call(hexo, hexo.locals.toObject());

  it('post with <= 10 tags should have no excerpt', () => {
    generatedPosts[0].data.excerpt.should.equal('<p>block 1</p>\n<p>block 2 <span>123</span></p>\n<div>block3</div>');
  });

  it('post with > 10 tags should have excerpt', () => {
    generatedPosts[1].data.excerpt.should.not.equal('');
    generatedPosts[1].data.excerpt.should.equal('<p>block 1</p>\n<p>block 2</p>\n<p>block 3</p>\n<p>block 4</p>\n<p>block 5</p>\n<p>block 6</p>\n<p>block 7</p>\n<p>block 8</p>\n<p>block 9</p>\n<p>block 10</p>');
  });

  it('post with <!-- more --> should return the way it is', () => {
    generatedPosts[2].data.excerpt.should.equal('');
  });

});

```

**Comment by meredrica** [comment]
finally :)

**Pull request merged**
